### ISSUE TITLE
[PE-D][Tester B] Extremely long names will cause the description of a person to disappear for createD

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T08-3/tp#257]
Similar to createP, adding a doctor with extremely long names will cause the "DOCTOR" status to disappear, making it hard to discern later whether this person is a patient or a doctor

Step 1: use createD command with the n/ field having an extremely long name
Step 2: execute the command
Step 3: Scroll down to view the new person that has been added by the command

Expected: "DOCTOR" status is displayed on the right side of the personcard

![image.png](https://raw.githubusercontent.com/LemonDrew/ped/main/files/143228cf-bbb4-4b8b-940a-cd89833e8c49.png)

Actual: "DOCTOR" status now disappears on the right side of the personcard

![image.png](https://raw.githubusercontent.com/LemonDrew/ped/main/files/d67bff47-47c6-4c6f-945a-323c9fbfe956.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: LemonDrew/ped#14

**Comment by Nigeltzy** [comment]
Sadly cannot implement changes for this due to feature freeze on UI, will include references to this in the UG instead.
