### ISSUE TITLE
[PE-D][Tester D] command result box is too small

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T08-3/tp#280]
![image.png](https://raw.githubusercontent.com/shuckycheese/ped/main/files/f8eacb38-e035-4c8f-86d4-aa24b3619c3e.png)

command results usually are too long for the command box to display in one shot, users will hence have to keep scrolling. considering how this is meant to mainly be a CLI app, I think the group can reformat the command results and command result box to fit everything inside so the users can see everything without having to constantly scroll

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: shuckycheese/ped#13

**Comment by Nigeltzy** [comment]
Thanks! Will treat as a nice to have considering feature freeze on UI

**Comment by Nigeltzy** [comment]
Low priority inclusion in DG
