### ISSUE TITLE
[PE-D][Tester D] phone number format

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T08-3/tp#291]
![image.png](https://raw.githubusercontent.com/shuckycheese/ped/main/files/f443deed-6ac4-40c0-9559-9f25d7053904.png)

I don't think it makes sense to have such phone numbers but your app does not do much checking to prevent such values from being passed in

consider adding some tests to prevent such inputs from being parsed

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: shuckycheese/ped#16

**Comment by Nigeltzy** [comment]
Thanks for the report! This is a valid point, for the team to consider:

- Feature freeze on enhancements
- Overzealous input validation, and whether we want to continue giving user the freedom to add such input.

![image](https://github.com/user-attachments/assets/0e347f31-2bcf-4b96-bd52-b40bb298471c)
